const { Pool } = require('pg');
const dotenv = require('dotenv');

dotenv.config();

const pool = new Pool({
  host: process.env.DB_HOST || 'localhost',
  port: process.env.DB_PORT || 5433,
  database: process.env.DB_NAME || 'blog_db',
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || 'postgres',
  max: 20,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 2000,
});

// Test connection
pool.on('connect', () => {
  console.log(' Connected to PostgreSQL database');
});

pool.on('error', (err) => {
  console.error('❌ Unexpected database error:', err);
});

// Initialize database tables
async function initializeDB() {
  const client = await pool.connect();
  try {
    // Create articles table if it doesn't exist
    await client.query(`
      CREATE TABLE IF NOT EXISTS articles (
        id SERIAL PRIMARY KEY,
        title VARCHAR(500) NOT NULL,
        content TEXT NOT NULL,
        excerpt TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);

    // Create index on created_at for faster queries
    await client.query(`
      CREATE INDEX IF NOT EXISTS idx_articles_created_at 
      ON articles(created_at DESC)
    `);

    console.log('✅ Database tables initialized');

    // Check if we have at least 3 articles, if not, generate some
    const result = await client.query('SELECT COUNT(*) FROM articles');
    const count = parseInt(result.rows[0].count);

    if (count < 3) {
      console.log(`📝 Found ${count} articles. Need at least 3. Will generate initial articles...`);
      // Initial articles will be generated by the scheduler
    }
  } catch (error) {
    console.error('❌ Error initializing database:', error);
    throw error;
  } finally {
    client.release();
  }
}

module.exports = {
  pool,
  initializeDB
};


